config/routes.rb
EShop::Application.routes.draw do
  root to: 'store#index', via: :get
  devise_for :users, controllers: { registrations: :registrations, sessions: :sessions, invitations: :invitations }

  resources :users
  resources :categories
  resources :line_items
  resources :shipments
  resources :payments
  resource :account, controller: :account, only: [:show]

  resources :addresses do
    member do
      delete :delete
    end
  end

  resources :orders do
    member do
      put :update_status
    end
  end

  resources :carts do
    member do
      put :update_shipment
    end

    collection do
      delete :purge
    end
  end

  resource :store,  only: [:index] do
    resources :products, controller: :store, only: [:index, :show] do
    end
  end

  resources :products do
    collection { get :search, to: 'products#index' }
  end

  # Handle non-existing routes
  get '*path', to: 'application#not_found'
end

app/models/order.rb
class Order < ActiveRecord::Base
  enum status: [ :beklemede, :onaylı, :kargoda, :tamamlandı ]

  belongs_to :user
  belongs_to :shipment
  belongs_to :payment

  belongs_to :address, foreign_key: :shipping_address_id
  belongs_to :billing_address, class_name: 'Address', foreign_key: :billing_address_id
  belongs_to :shipping_address, class_name: 'Address', foreign_key: :shipping_address_id

  has_many :line_items, -> { includes(product: [:vat]) }, dependent: :destroy

  validates :shipping_address_id, :shipment_id, :payment_id, presence: true

  before_create :set_billing_address

  def set_billing_address
    self.billing_address_id = shipping_address_id  if billing_address_id.nil?
  end

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      line_item = item.dup
      line_item.product.decrease_quantity line_item.quantity
      line_item.cart_id = nil
      line_item.save!
      line_items << line_item
    end
  end

  def subtotal
    line_items.to_a.sum(&:subtotal)
  end

  def total
    line_items.to_a.sum { |item| item.total } + shipment.fee
  end

  def count
    line_items.to_a.sum(&:quantity)
  end

  def taxes
    line_items.to_a.sum(&:tax)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update_status, :destroy]
  after_action :verify_authorized, only: [:show, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    authorize :orders, :index?

    orders = policy_scope(Order).includes(:user, :shipment, :payment, :line_items)
    @items = find_and_paginate(orders, order: 'updated_at DESC')

    render(partial: 'orders', layout: false) and return if request.xhr?
  end

  def show
    authorize @order

    respond_to do |format|
      format.html
      format.js
      format.pdf do
        send_data OrderPdf.new(@order, view_context).render, filename: "order_#{@order.id}", type: "application/pdf", disposition: "inline"
      end
    end

  end

  def new
    @cart = current_cart
    @shipments = Shipment.all
    @address = Address.new

    if @cart.line_items.empty?
      redirect_to root_path, notice: _('Your cart is empty!') and return
    else
      @order = Order.new
    end
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.add_line_items_from_cart(@current_cart)

    respond_to do |format|
      if @order.valid? && @order.save
        @current_cart.destroy
        session[:cart_id] = nil

        # FIXME: Send notification email
        UserMailer.order_confirmation(current_user, @order).deliver_now

        format.html { redirect_to root_path, notice: _('Thank you for your order!') }
      else
        format.html { render action: 'new' }
      end
    end
  end


  def update_status
    prev_status = @order.status

    if @order.update(order_params)
      notice = "Sipariş durumu '%s' durumundan '%s' durumuna dönüştürüldü." % [prev_status.humanize, order_params[:status].humanize]
      redirect_to orders_path, notice: notice
    else
      redirect_to orders_path, error: _('Can not change order status')
    end

  end

  # def update
  #   respond_to do |format|
  #     if @order.update(order_params)
  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # FIXME: Move admin actions to the separate controller!
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
  def set_order
    @order = policy_scope(Order).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:shipping_address_id, :billing_address_id, :shipment_id, :payment_id, :status)
  end

end

app/views/orders/_address.haml
.panel-heading
  %h4.panel-title
    %span.round 1
    = _('Shipping and Billing address')

#address.panel-collapse.collapse.in
  .panel-body
    .row
      .col-xs-6
        %b= _('Shipping address')
      .col-xs-6
        .text-right
          = link_to _('Add new address'), '#new_address', class: 'text-link', data: { target: '#address_modal', toggle: 'modal' }

    - if current_user.addresses.present?
      #shipping_addresses
        - current_user.addresses.each_with_index do |address, index|
          .radio
            %label
              = form.radio_button :shipping_address_id, address.id, checked: (address == current_user.addresses.first)
              = address.full_address

      %hr

      .row
        .col-xs-6
          %b= _('Billing address')
        .col-xs-6
          .text-right
            = link_to _('Add new address'), '#new_address', class: 'text-link', data: { target: '#address_modal', toggle: 'modal' }

      .checkbox
        %label
          = check_box_tag :bill_to_shipping, true, checked: true
          %label= _('billing address is same as shipping address')

      #billing_addresses.hidden
        - current_user.addresses.each_with_index do |address, index|
          .radio.disabled
            %label
              = form.radio_button :billing_address_id, address.id, checked: (address == current_user.addresses.last), disabled: true
              = address.full_address

    - else
      %h5
        %i.fa.fa-info-circle
        = _('Your addresses list is empty, please add at least one address')
      .row
        .col-xs-12
          = link_to _('Add new address'), '#new_address', class: 'text-link', data: { target: '#address_modal', toggle: 'modal' }

    %hr
    .pull-left
      = icon_link_to _('Back to cart'), cart_path(@current_cart), { class: 'btn btn-default' }, 'fa-chevron-circle-left'

    .pull-right
      = icon_link_to _('Next'), '#shipping', { class: 'btn btn-next btn-success', data: { parent: '#accordion', toggle: 'collapse', step: 2 }}, 'fa-chevron-circle-right'

app/views/orders/_orders.haml
- @items.each do |order|
  %tr
    %td
      = form_tag update_status_order_path(order), id: :update_status, method: :put do
        - labels = { beklemede: 'btn-default', onaylı: 'btn-default', kargoda: 'btn-primary', tamamlandı: 'btn-success'}
        - icons = { beklemede: 'fa-clock-o', onaylı: 'fa-archive', kargoda: 'fa-truck', tamamlandı: 'fa-check-circle'}
        .btn-group
          %button.btn.btn-sm.btn-default.dropdown-toggle{ class: labels[order.status.to_sym], data: { toggle: :dropdown }}
            %i{ class: "fa #{icons[order.status.to_sym]}"}
            = order.status.humanize
            %span.caret
          %ul.dropdown-menu
            - Order.statuses.except(order.status).keys.each_with_index do |status, index|
              - radio_id = "ex#{order.id}_#{index+1}"
              %li
                %input{id: radio_id, name: "order[status]", type: :radio, value: status}
                %label{for: radio_id, data: { target: "##{radio_id}"}}
                  %i{ class: "fa #{icons[status.to_sym]}"}
                  = status.humanize
    %td= order.user.name
    %td= I18n.localize(order.created_at)
    %td= order.payment.title
    %td= number_to_currency order.total
    %td.text-right
      = icon_link_to '', order, { class: 'btn btn-sm btn-default' }, 'fa-eye'
      = icon_link_to '', order_path(order, format: 'pdf'), { class: 'btn btn-sm btn-default' }, 'fa-print'
      = icon_link_to '', order, { data: {confirm: _('Are you sure?') }, method: :delete, class: 'btn btn-sm btn-default' }, 'fa-trash-o'

= table_pagination(@items)

app/views/orders/_payment.haml
.panel-heading
  %h4.panel-title
    %span.round 3
    = _('Payment method')

#payment.panel-collapse.collapse
  .panel-body
    - Payment.all.each_with_index do |payment, index|
      .radio
        %label
          = form.radio_button :payment_id, payment.id, checked: index.zero?
          = _(payment.title)

    %hr
    .pull-left= icon_link_to _('Back'), '#shipping', { class: 'btn btn-back btn-default', data: { parent: '#accordion', toggle: 'collapse', step: 2 } }, 'fa-chevron-circle-left'
    .pull-right= icon_link_to _('Next'), '#summary', { class: 'btn btn-next btn-success', data: { parent: '#accordion', toggle: 'collapse', step: 4 }}, 'fa-chevron-circle-right'

app/views/orders/_shipping.haml
.panel-heading
  %h4.panel-title
    %span.round 2
    = _('Shipping method')

#shipping.panel-collapse.collapse{ data: { endpoint: update_shipment_cart_path(current_cart) }}
  .panel-body
    - Shipment.all.each_with_index do |shipment, index|
      .radio
        %label
          = form.radio_button :shipment_id, shipment.id, checked: shipment.default
          = "#{shipment.provider} #{shipment.title}"
          %b= " #{number_to_currency(shipment.fee)}"
          - if Shipment.default == shipment
            %span.label.label-default Standard


    %hr
    .pull-left= icon_link_to _('Back'), '#address', { class: 'btn btn-back btn-default', data: { parent: '#accordion', toggle: 'collapse', step: 1 } }, 'fa-chevron-circle-left'
    .pull-right= icon_link_to _('Next'), '#payment', { class: 'btn btn-next btn-success', data: { parent: '#accordion', toggle: 'collapse', step: 3 }}, 'fa-chevron-circle-right'

app/views/orders/_summary.haml
.panel-heading
  %h4.panel-title
    %span.round 4
    = _('Order summary')

#summary.panel-collapse.collapse
  .panel-body
    %table.table.table-hover.table-responsive
      %thead
        %tr
          %th.hidden-xs{width: '5%'}= _('Image')
          %th= _('Title')
          %th= _('Price')
          %th= _('Quantity')
          %th.hidden-xs= _('Subtotal')
          %th.hidden-xs= _('VAT')
          %th= _('Total')

      %tbody
        - @current_cart.line_items.each do |item|
          %tr
            %td.hidden-xs= product_image_tag item.product
            %td= link_to item.product.title, store_product_path(item.product)
            %td= number_to_currency(item.price)
            %td= item.quantity
            %td.hidden-xs= number_to_currency(item.subtotal)
            %td.hidden-xs= number_to_percentage(item.product.vat.rate, precision: 0)
            %td= number_to_currency(item.total)

        %tr.text-muted
          %td.hidden-xs
          %td.hidden-xs
          %td.hidden-xs
          %td{ colspan: 3 }= _('Subtotal')
          %td{ colspan: 2 }
            = number_to_currency(@current_cart.subtotal)
        %tr.text-muted
          %td.no-line.hidden-xs
          %td.no-line.hidden-xs
          %td.no-line.hidden-xs
          %td.no-line{ colspan: 3 }= _('incl. VAT')
          %td.no-line{ colspan: 2 }
            = number_to_currency(@current_cart.taxes)
        %tr.text-muted
          %td.no-line.hidden-xs
          %td.no-line.hidden-xs
          %td.no-line.hidden-xs
          %td.no-line{ colspan: 3 }= _('Shipment')
          %td.no-line{ colspan: 2 }
            = number_to_currency((@current_cart.shipment || Shipment.default).fee)
        %tr
          %td.hidden-xs
          %td.hidden-xs
          %td.hidden-xs
          %td{ colspan: 3 }
            %b= _('Total exc. shipping')
          %td{ colspan: 2 }
            %b= number_to_currency(@current_cart.total)

    %hr
    .pull-left= icon_link_to _('Back'), '#payment', { class: 'btn btn-back btn-default', data: { parent: '#accordion', toggle: 'collapse', step: 3 } }, 'fa-chevron-circle-left'
    .pull-right= submit_tag _('Place order'), class: 'btn btn-success'

app/views/orders/index.haml
%h4.page-header.no-margin= _('Orders')

.panel.panel-default
  .panel-body
    %table.table.table-hover
      %thead
        %tr
          %th= _('Status')
          %th= _('Customer')
          %th= _('Date')
          %th= _('Payment')
          %th= _('Total')
          %th{ colspan: 3, width: '25%'}
            = ransack_search_form_for(orders_path, :user_name_cont)
      %tbody{id: controller_name}
        = render partial: controller_name

app/views/orders/new.haml
- breadcrumb :checkout

%br

.panel.panel-default
  .panel-heading
    .progress-steps
      .progress-timeline
        %ul.progress-timeline-completion{ step: 1, data: { step: 2 }}
          %li.step.active{ rel: :tooltip, title: _('Shipping and Billing address') }
            %a{ href: '#address', data: { toggle: 'collapse', parent: '#accordion', step: 1 }}
              %i.fa.fa-envelope.icon
          %li.step{ rel: :tooltip, title: _('Shipping method') }
            %a{ href: '#shipping', data: { toggle: 'collapse', parent: '#accordion', step: 2 }}
              %i.fa.fa-truck.icon
          %li.step{ rel: :tooltip, title: _('Payment method') }
            %a{ href: '#payment', data: { toggle: 'collapse', parent: '#accordion', step: 3 }}
              %i.fa.fa-credit-card.icon
          %li.step{ rel: :tooltip, title: _('Order summary') }
            %a{ href: '#summary', data: { toggle: 'collapse', parent: '#accordion', step: 4 }}
              %i.fa.fa-list.icon

  .panel-body
    = form_for @order, html: { role: 'form', class: 'new_order_form'} do |form|
      = render 'layouts/errors', object: @order

      #accordion.panel-group
        .panel
          = render partial: 'address', locals: { form: form }
        .panel
          = render partial: 'shipping', locals: { form: form }
        .panel
          = render partial: 'payment', locals: { form: form }
        .panel
          = render partial: 'summary', locals: { form: form }

    = render 'addresses/modal', address: Address.new

app/views/orders/show.haml
- breadcrumb :order, @order

.panel.panel-default
  .panel-heading
    .progress-steps
      .progress-timeline
        - status = @order.status.to_sym
        %ul.progress-timeline-completion{ step: Order.statuses[@order.status] + 1 }
          %li.step.active{ rel: :tooltip, title: _('Accepted') }
            %i.fa.fa-clock-o
          %li.step{ class: [:in_progress, :shipped, :completed].include?(status) ? 'active' : '', rel: :tooltip, title: _('In progress') }
            %i.fa.fa-archive
          %li.step{ class: [:shipped, :completed].include?(status) ? 'active' : '', rel: :tooltip, title: _('Shipped') }
            %i.fa.fa-truck
          %li.step{ class: @order.completed? ? 'active' : '', rel: :tooltip, title: _('Completed') }
            %i.fa.fa-check

  .panel-body
    .row
      .col-xs-12
        %h3
          = _("Order #%d") % @order.id
          .pull-right
            = icon_link_to "", order_path(@order, format: 'pdf'), 'fa-print'

        %hr
          .row
            .col-xs-6
              %address
                %strong= _('Billing address')
                %br
                  = @order.billing_address.recipient
                  %br
                    = "#{@order.billing_address.street}"
                    %br
                      = "#{@order.billing_address.zip_code} #{@order.billing_address.city}"

            .col-xs-6.text-right
              %address
                %strong= _('Shipping address')
                %br
                  = @order.address.recipient
                  %br
                    = "#{@order.address.street}"
                    %br
                      = "#{@order.address.zip_code} #{@order.address.city}"
          .row
            .col-xs-6
              %address
                %strong= _('Payment method')
                %br
                  = _(@order.payment.title)

            .col-xs-6.text-right
              %address
                %strong= _('Order date')
                %br
                  = I18n.localize(@order.created_at)
                  %br
                    %br
    .row
      .col-md-12
        .panel.panel-default
          .panel-heading
            %b= _('Order summary')
          .panel-body
            %table.table.table-condensed
              %thead
                %tr
                  %td #
                  %td
                    %strong= _('Product')
                  %td
                    %strong= _('Price')
                  %td
                    %strong= _('Quantity')
                  %td.text-right
                    %strong= _('Total')

              %tbody
                - @order.line_items.each_with_index do |item, index|
                  %tr
                    %td= index+1
                    %td= item.product.title
                    %td= number_to_currency(item.price)
                    %td= item.quantity
                    %td.text-right= number_to_currency(item.total)
              %tr
                %td.thick-line.text-right{ colspan: 4 }
                  %strong= _('Subtotal')
                %td.thick-line.text-right= number_to_currency(@order.subtotal)
              %tr
                %td.no-line.text-right{ colspan: 4 }
                  %strong= _('Shipment')
                %td.no-line.text-right= number_to_currency(@order.shipment.fee)
              %tr
                %td.no-line.text-right{ colspan: 4 }
                  %strong= _('Total')
                %td.no-line.text-right= number_to_currency(@order.total)