config/routes.rb
EShop::Application.routes.draw do
  root to: 'store#index', via: :get
  devise_for :users, controllers: { registrations: :registrations, sessions: :sessions, invitations: :invitations }

  resources :users
  resources :categories
  resources :line_items
  resources :shipments
  resources :payments
  resource :account, controller: :account, only: [:show]

  resources :addresses do
    member do
      delete :delete
    end
  end

  resources :orders do
    member do
      put :update_status
    end
  end

  resources :carts do
    member do
      put :update_shipment
    end

    collection do
      delete :purge
    end
  end

  resource :store,  only: [:index] do
    resources :products, controller: :store, only: [:index, :show] do
    end
  end

  resources :products do
    collection { get :search, to: 'products#index' }
  end

  # Handle non-existing routes
  get '*path', to: 'application#not_found'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :shipment
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  class << self
    def purge
      Cart.where("updated_at  <?", 2.hours.ago).destroy_all
    end
  end

  def add_item(product_id, quantity)
    quantity = quantity.to_i
    line_item = line_items.find_by(product_id: product_id)

    if line_item
      quantity = line_item.quantity + quantity
      update_item(line_item.id, quantity)
    else
      product = Product.find(product_id)
      line_item = line_items.create(product_id: product.id, price: product.price, quantity: quantity)
    end

    line_item
  end

  def update_item(line_item_id, quantity)
    quantity = quantity.to_i
    line_item = line_items.find(line_item_id)

    if quantity <= line_item.max_quantity
      ActiveRecord::Base.transaction do
        line_item.product.update(reserved_count: quantity)
        line_item.update_attributes(quantity: quantity)
      end
    end
  end

  def empty?
    line_items.count.zero?
  end

  def count
    line_items.sum(:quantity)
  end

  def subtotal
    line_items.to_a.sum { |item| item.total }
  end

  def total
    line_items.to_a.sum { |item| item.total } + shipping
  end

  def taxes
    line_items.to_a.sum { |item| item.tax }
  end

  def shipping
    shipment.try(:fee) || Shipment.default.fee
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:show, :update, :destroy]
  after_action :verify_authorized, except: [:show, :update, :destroy]

  def index
    authorize :carts, :index?

    @items = find_and_paginate(order: 'updated_at DESC')
    render(partial: 'carts', layout: false) and return if request.xhr?
  end

  def show
    redirect_to root_path, notice: _('Your cart is empty!') if current_cart.empty?
  end

  def update_shipment
    current_cart.update(shipment_id: params[:shipment_id])
    render(partial: 'orders/summary', layout: false) and return if request.xhr?
  end

  def purge
    authorize :carts, :purge?

    Cart.purge
    redirect_to carts_path
  end

  def destroy
    cart = (current_user && current_user.admin?) ? Cart.find(params[:id]) : current_cart

    if cart.destroy
      flash.notice = _('Cart was successfully destroyed.')
    else
      flash.error = _('Something went wrong')
    end

    redirect_to_back_or_default root_path

  end
end

app/views/carts/_items.haml
%table.table.table-hover.table-responsive
  %thead
    %tr
      %th.hidden-xs{width: '5%'}= _('Image')
      %th= _('Title')
      %th= _('Price')
      %th= _('Quantity')
      %th.hidden-xs= _('Subtotal')
      %th.hidden-xs= _('VAT')
      %th= _('Total')
      %th ---

  %tbody
    - @current_cart.line_items.each do |item|
      %tr
        %td.hidden-xs= product_image_tag item.product
        %td= link_to item.product.title, store_product_path(item.product)
        %td= number_to_currency(item.price)
        %td
          .visible-xs= item.quantity
          .hidden-xs
            = form_for item, method: :patch, class: 'form-inline' do
              = quantity_field_tag item.quantity
        %td.hidden-xs= number_to_currency(item.subtotal)
        %td.hidden-xs= number_to_percentage(item.product.vat.rate, precision: 0)
        %td= number_to_currency(item.total)
        %td= icon_link_to '', item, { class: 'text-danger', method: :delete}, 'fa-trash-o'

    %tr.text-muted
      %td.hidden-xs
      %td.hidden-xs
      %td.hidden-xs
      %td{ colspan: 3 }= _('Subtotal')
      %td{ colspan: 2 }
        = number_to_currency(@current_cart.subtotal)
    %tr.text-muted
      %td.no-line.hidden-xs
      %td.no-line.hidden-xs
      %td.no-line.hidden-xs
      %td.no-line{ colspan: 3 }= _('incl. VAT')
      %td.no-line{ colspan: 2 }
        = number_to_currency(@current_cart.taxes)
    %tr
      %td.hidden-xs
      %td.hidden-xs
      %td.hidden-xs
      %td{ colspan: 3 }
        %b= _('Total exc. shipping')
      %td{ colspan: 2 }
        %b= number_to_currency(@current_cart.subtotal)

app/views/carts/show.haml
- breadcrumb :cart, @current_cart

.panel.panel-default
  .panel-heading
    .panel-title
      .row
        .col-xs-6.col-md-6
          %h4
            %i.fa.fa-shopping-cart
            = _('Your Cart')

        .col-xs-6.col-md-6.text-right
          - unless @current_cart.total.zero?
            = link_to _('Empty cart'), @current_cart, data: {confirm: _('Are you sure?')}, method: :delete, class: 'btn btn-danger'

  .panel-body
    - if @current_cart.total.zero?
      %h4=_('Your cart is empty!')
    - else
      #items= render 'items'

    %hr

    .row
      .col-xs-12.col-sm-6.col-md-3.col
        %p= link_to _('Continue shopping'), root_path, class: 'btn btn-default btn-block'
      .col-xs-12.col-sm-6.col-md-3.col-md-offset-6
        %p= link_to _('Proceed to Checkout'), new_order_path, class: 'btn btn-success btn-block'

app/views/carts/update.js.erb
<%- if @current_cart.empty? %>
  window.location.replace("/")
<% else %>
  $("#items").html("<%= escape_javascript(render :partial=> 'items') %>");
<% end %>