config/routes.rb
EShop::Application.routes.draw do
  root to: 'store#index', via: :get
  devise_for :users, controllers: { registrations: :registrations, sessions: :sessions, invitations: :invitations }

  resources :users
  resources :categories
  resources :line_items
  resources :shipments
  resources :payments
  resource :account, controller: :account, only: [:show]

  resources :addresses do
    member do
      delete :delete
    end
  end

  resources :orders do
    member do
      put :update_status
    end
  end

  resources :carts do
    member do
      put :update_shipment
    end

    collection do
      delete :purge
    end
  end

  resource :store,  only: [:index] do
    resources :products, controller: :store, only: [:index, :show] do
    end
  end

  resources :products do
    collection { get :search, to: 'products#index' }
  end

  # Handle non-existing routes
  get '*path', to: 'application#not_found'
end

app/models/category.rb
class Category < ActiveRecord::Base
  translates :title, fallbacks_for_empty_translations: true
  globalize_accessors locales: [], attributes: [:title]

  has_many :products

  validates :title, presence: true, uniqueness: true

  default_scope {
    includes(:translations)
  }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  def index
    authorize :categories, :index?

    @items = find_and_paginate(order: 'category_translations.title ASC')
    render(partial: 'categories', layout: false) and return if request.xhr?
  end

  def show
    authorize @category
  end

  def edit
    authorize @category
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category

    if @category.save
      redirect_to categories_path, notice: _('Category was successfully created.')
    else
      render action: 'new'
    end
  end

  def update
    authorize @category

    if @category.update(category_params)
      redirect_to categories_path, notice: _('Category was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    authorize @category

    @category.destroy
    redirect_to categories_path, notice: _('Category was successfully destroyed.')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category ||= Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(*Category.globalize_attribute_names, :title)
    end
end

app/views/categories/_categories.haml
- @items.each do |category|
  %tr
    %td= category.title
    %td= link_to "#{category.products_count} ürün", category_path(category)
    %td.text-right
      = icon_link_to '', category, { class: 'btn btn-sm btn-default' }, 'fa-eye'
      = icon_link_to '', edit_category_path(category), { class: 'btn btn-sm btn-default' }, 'fa-edit'
      = icon_link_to '', category, { data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-sm btn-default' }, 'fa-trash-o'


= table_pagination(@items)

app/views/categories/_form.haml
.panel.panel-default
  = form_for @category, html: { class: "form-horizontal" } do |f|
    .panel-heading
      %h4.page-header.no-margin= _("%s category") % action
      = render 'layouts/errors', object: @category

    .panel-body
      = translation_fields_for @category, :title, _('Title')

    .panel-footer
      = f.submit _('Save'), class: 'btn btn-success'
      = link_to _('Back'), categories_path

app/views/categories/edit.haml
= render 'form', action: _('Edit')

app/views/categories/index.haml
%h4.page-header.no-margin
  = _('Categories')
  .pull-right
    = link_to _('New category'), new_category_path, class: 'btn btn-xs btn-success'

.panel.panel-default
  .panel-body
    %table.table.table-hover
      %thead
        %tr
          %th= _('Title')
          %th= _('Product count')
          %th{ colspan: 3, width: '25%' }
            = ransack_search_form_for(categories_path, :translations_title_cont)
      %tbody{id: controller_name}
        = render partial: controller_name

app/views/categories/new.haml
= render 'form', action: 'New'

app/views/categories/show.haml
.panel
  .panel-body
    %h4.page-header= _('Category')

    %dl.dl-horizontal
      - Category.globalize_locales.each do |locale|
        %dt= _("Title %s:") % locale.upcase
        %dd= @category.send("title_#{locale}")

    %dl.dl-horizontal
      %dt= _('Products:')
      - if @category.products.exists?
        - @category.products.each_with_index do |product, index|
          %dd
            = icon_link_to "#{index+1}. #{product.title}", edit_product_path(product), { class: '' }, 'fa-edit'
      - else
        %dd
          = link_to _('New product'), new_product_path

  .panel-footer
    = link_to _('Edit'), edit_category_path(@category), class: 'btn btn-default'
    = link_to _('Back'), categories_path