config/routes.rb
EShop::Application.routes.draw do
  root to: 'store#index', via: :get
  devise_for :users, controllers: { registrations: :registrations, sessions: :sessions, invitations: :invitations }

  resources :users
  resources :categories
  resources :line_items
  resources :shipments
  resources :payments
  resource :account, controller: :account, only: [:show]

  resources :addresses do
    member do
      delete :delete
    end
  end

  resources :orders do
    member do
      put :update_status
    end
  end

  resources :carts do
    member do
      put :update_shipment
    end

    collection do
      delete :purge
    end
  end

  resource :store,  only: [:index] do
    resources :products, controller: :store, only: [:index, :show] do
    end
  end

  resources :products do
    collection { get :search, to: 'products#index' }
  end

  # Handle non-existing routes
  get '*path', to: 'application#not_found'
end

app/views/layouts/_errors.haml
- if object.errors.any?
  .alert.fade.in.alert-danger.alert-dismissable
    %button.close{ 'aria-hidden' => :true, 'data-dismiss' => :alert, type: 'button' }  ×
    %ol
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg, id: "error_#{msg}" if msg.is_a?(String)

app/views/layouts/_messages.haml
/ Flash messages styled for Bootstrap 3.0
#rails_flash
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div.alert{ class: (name.to_s == 'notice') ? 'alert-success' : 'alert-danger'}
        %button.close{ type: :button, 'data-dismiss' => :alert, 'aria-hidden' => :true } ×
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.haml
/ Navigation styled for Bootstrap 3.0
.navbar.navbar-default.navbar-fixed-top{ role: 'navigation' }
  .container
    .navbar-header
      %button.navbar-toggle{ type: :button, data: { toggle: :collapse, target: '.navbar-collapse' }}
        %span.sr-only Toggle navigation
        %i.fa.fa-bars.fa-lg
      = icon_link_to 'E-Ticaret', root_path, { class: 'navbar-brand' }, ''

      .visible-xs.navbar-collapse.pull-right
        - css_classes = current_cart.empty? ? 'btn btn-default navbar-btn' : 'btn btn-default btn-success navbar-btn'
        = icon_link_to '', cart_path(current_cart), { class: css_classes }, 'fa-shopping-cart'

    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - unless [new_user_registration_url, new_user_session_url, new_user_password_url].include? request.url
          - if current_cart.empty?
            %li.disabled
              = icon_link_to "#{_('Cart')} (0)", '#', { class: :disabled }, 'fa-shopping-cart'
          - else
            %li{ class: controller_name == 'carts' ? 'active' : '' }
              = icon_link_to "#{_('Cart')} (#{current_cart.count} | #{number_to_currency(current_cart.subtotal)} )", cart_path(current_cart), 'fa-shopping-cart'

        %li.dropdown
          - if user_signed_in?
            %li.dropdown{ class: controller_name == 'account' ? 'active' : '' }
              %a.dropdown-toggle{ 'data-toggle' => :dropdown, href: '#' }
                %i.fa.fa-user
                = current_user.name
                %b.caret

              %ul.dropdown-menu
                %li= icon_link_to _('My Account'), account_path, 'fa-gear'
                %li= icon_link_to _('Sign out'), destroy_user_session_path, { method: 'delete' }, 'fa-sign-out'
          - else
            %li.dropdown
              %a.dropdown-toggle{ 'data-toggle' => :dropdown, href: '#' }
                %i.fa.fa-lg.fa-sign-in
                = "#{_('Sign in')} / #{_('Sign up')}"
                %b.caret
              %ul.dropdown-menu
                %li= link_to _('Sign in'), new_user_session_path, class: 'navbar-link'
                %li= link_to _('Sign up'), new_user_registration_path, class: 'navbar-link'

- if user_signed_in? && current_user.admin?
  .subnav.navbar.navbar-default
    .container
      %ul.nav.navbar-nav.navbar-link
        %li{ class: controller_name == 'orders' ? 'active' : '' }
          = link_to _('Orders'), orders_path

        %li{ class: controller_name == 'categories' ? 'active' : '' }
          = link_to _('Categories'), categories_path

        %li{ class: controller_name == 'products' ? 'active' : '' }
          = link_to _('Products'), products_path

        %li{ class: controller_name == 'users' ? 'active' : '' }
          = link_to _('Users'), users_path

        %li{ class: controller_name == 'address' ? 'active' : '' }
          = link_to _('Addresses'), addresses_path

        %li{ class: controller_name == 'shipments' ? 'active' : '' }
          = link_to _('Shipments'), shipments_path

        %li{ class: controller_name == 'payments' ? 'active' : '' }
          = link_to _('Payments'), payments_path


-# .subnav.navbar.navbar-default
-#   .container
-#     %ul.nav.navbar-nav.navbar-link
-#       %li{ class: params[:category_name_cont].nil? ? 'active' : '' }
-#         = link_to _('All categories'), root_path(view: @view), remote: :true
-#       - Category.all.each do |cat|
-#         - name = "#{cat.name} (#{cat.products_count})"
-#         - path = root_path(q: {'category_name_cont' => cat.name}, view: @view)
-#         %li{ class: cat.name == params[:category_name_cont] ? 'active' : '' }
-#           = link_to name, path, "data-toggle" => "tab", 'data-url' => path, remote: :true

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title E-Ticaret
    %meta{ name: :description, content: 'E-Ticaret' }
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }
    = stylesheet_link_tag "application", media: "all", 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    #wrap
      %header
        = render 'layouts/navigation'
      %main
        .container
          = render 'layouts/messages'
          = breadcrumbs style: :bootstrap
          = yield


    %footer
      .container
        .col-md-12.no-padding
          &copy; Levent Sencer ŞAHİN